# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b017d9df929a489c824b4e5d2f1a9a86adaff11664ca55c522d932fe748d92887604567133bc33b85da27eea88f93adcbd522c39b8f437b1660084b0db2d2272

test:
  secret_key_base: 085ea4e5e87fcda03820b0cd22cec471171c54cf2c14793eaad1c7d2c069623314feda5f16cccd39de4f36ce72664fbdb13155d6c5e2c8b3c9c2ffdf62693333

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
